# permissions for end users to view appsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: appsecret-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: app-secrets-operator
    app.kubernetes.io/part-of: app-secrets-operator
    app.kubernetes.io/managed-by: kustomize
  name: appsecret-viewer-role
rules:
- apiGroups:
  - secrets.toni.systems
  resources:
  - appsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - secrets.toni.systems
  resources:
  - appsecrets/status
  verbs:
  - get
