apiVersion: secrets.toni.systems/v1alpha1
kind: AppSecret
metadata:
  name: app-secret
  namespace: default
  labels:
    app: app-secret
spec:
  env:
    SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
    SPRING_DATASOURCE_USERNAME: "secret://rds-credentials/username"
    SPRING_DATASOURCE_PASSWORD: "secret://rds-credentials/password"
    GITHUB_TOKEN: "secret://github/gh-token"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: default
  labels:
    app: myapp
  annotations:
    "secrets.toni.systems/app-secret": "default/app-secret"
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: nginx:latest
          envFrom:
            - secretRef:
                name: app-secret
