name: build and release

on:
  release:
    types: [published]

env:
  TAG: "${{ github.ref_name }}"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          driver: docker
      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}
      - name: Install kustomize
        uses: imranismail/setup-kustomize@v2
      - name: Set version
        run: |
          echo "VERSION=${TAG//v/}" >>${GITHUB_ENV}
      - name: Generate release yaml
        run: make static
      - name: Build docker image
        run: |
          make docker-build
          make docker-push
      - name: Upload file to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.PAT }}
          file: config/release/static.yaml
          asset_name: release.yaml
          tag: ${{ env.TAG }}
          overwrite: true
